name: Build and push images (pandoc)

on:
  workflow_dispatch:

concurrency:
  group: pandoc
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMG_NAME: pandoc
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  vars:
    runs-on: ubuntu-latest

    steps:
      - run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    outputs:
      tag_base: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMG_NAME }}
      tag_end: ${{ env.DATE }}
      context: "{{defaultContext}}:${{ env.IMG_NAME }}"
      labels: |
        org.opencontainers.image.source=${{ github.event.repository.html_url }}
        org.opencontainers.image.description=${{ github.event.repository.description }}
        org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
        org.opencontainers.image.revision=${{ github.sha }}

  build-and-push-images:
    runs-on: ubuntu-latest
    needs: vars

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ${{ needs.vars.outputs.context }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          provenance: false
          labels: ${{ needs.vars.outputs.labels }}
          tags: |
            ${{ needs.vars.outputs.tag_base }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end }}
