name: Build and push images (raku)

on:
  push:
    branches:
      - main
    paths:
      - raku/**
  workflow_dispatch:

concurrency:
  group: raku
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: raku
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  vars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          set -eux
          RAKUDO_VERSION="$(grep -oP '(?<=RAKUDO_VERSION=)[0-9.]+' "${{ env.IMAGE_NAME }}/Dockerfile")"
          DEBIAN_VERSION="$(grep -oP '(?<=DEBIAN_VERSION=)[0-9.]+' "${{ env.IMAGE_NAME }}/Dockerfile")"
          echo "RAKUDO_VERSION=$RAKUDO_VERSION" >> $GITHUB_ENV
          echo "DEBIAN_VERSION=$DEBIAN_VERSION" >> $GITHUB_ENV

    outputs:
      tag_base: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
      tag_end1: ${{ env.RAKUDO_VERSION }}
      tag_end2: ${{ env.RAKUDO_VERSION }}-debian${{ env.DEBIAN_VERSION }}
      context: "{{defaultContext}}:${{ env.IMAGE_NAME }}"
      labels: |
        org.opencontainers.image.source=${{ github.event.repository.html_url }}
        org.opencontainers.image.description=${{ github.event.repository.description }}
        org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
        org.opencontainers.image.revision=${{ github.sha }}

  build-and-push-images:
    runs-on: ubuntu-latest
    needs: vars

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and check image
        uses: docker/build-push-action@v6
        with:
          target: check
          context: ${{ needs.vars.outputs.context }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ env.PLATFORMS }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          target: runtime
          context: ${{ needs.vars.outputs.context }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ env.PLATFORMS }}
          push: true
          provenance: false
          labels: ${{ needs.vars.outputs.labels }}
          tags: |
            ${{ needs.vars.outputs.tag_base }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end1 }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end2 }}
