name: Build and push images (mlflow)

on:
  workflow_dispatch:

concurrency:
  group: mlflow
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMG_NAME: mlflow
  PLATFORMS: linux/amd64,linux/arm64
  MLFLOW_VERSION: 2.17.0
  DEBIAN_VERSION: 12
  DEBIAN_RELEASE: bookworm

jobs:
  vars:
    runs-on: ubuntu-latest

    steps:
      - run: pwd

    outputs:
      tag_base: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMG_NAME }}
      tag_end1: ${{ env.MLFLOW_VERSION }}
      tag_end2: ${{ env.MLFLOW_VERSION }}-debian${{ env.DEBIAN_VERSION }}
      context: "{{defaultContext}}:${{ env.IMG_NAME }}"
      labels: |
        org.opencontainers.image.source=${{ github.event.repository.html_url }}
        org.opencontainers.image.description=${{ github.event.repository.description }}
        org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
        org.opencontainers.image.revision=${{ github.sha }}
      build_args: |
        MLFLOW_VERSION=${{ env.MLFLOW_VERSION }}
        DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}
        DEBIAN_RELEASE=${{ env.DEBIAN_RELEASE }}

  build-and-push-images:
    runs-on: ubuntu-latest
    needs: vars

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ${{ needs.vars.outputs.context }}
          build-args: ${{ needs.vars.outputs.build_args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ env.PLATFORMS }}
          push: true
          provenance: false
          labels: ${{ needs.vars.outputs.labels }}
          tags: |
            ${{ needs.vars.outputs.tag_base }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end1 }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end2 }}
