name: Build and push Docker images (python)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'

concurrency:
  group: python
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMG_NAME: python
  TAG_BASE: ghcr.io/${{ github.actor }}/${{ env.IMG_NAME }}
  CONTEXT: '{{defaultContext}}:${{ env.IMG_NAME }}'
  LABELS: |
    org.opencontainers.image.source=${{ github.event.repository.html_url }}
    org.opencontainers.image.description=${{ github.event.repository.description }}
    org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
    org.opencontainers.image.revision=${{ github.sha }}
  PYTHON_VERSION: 3.11
  DEBIAN_VERSION: 12
  DEBIAN_RELEASE: debian${{ env.DEBIAN_VERSION }}
  BUILD_ARGS: |
    PYTHON_VERSION=${{ env.PYTHON_VERSION }}
    DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and check Docker image (check)
        uses: docker/build-push-action@v5
        with:
          target: check
          context: ${{ env.CONTEXT }}
          build-args: ${{ env.BUILD_ARGS }}

      - name: Build and push Docker image (latest)
        uses: docker/build-push-action@v5
        with:
          target: latest
          context: ${{ env.CONTEXT }}
          build-args: ${{ env.BUILD_ARGS }}
          push: true
          labels: ${{ env.LABELS }}
          tags: |
            ${{ env.TAG_BASE }}
            ${{ env.TAG_BASE }}:${{ env.PYTHON_VERSION }}
            ${{ env.TAG_BASE }}:${{ env.PYTHON_VERSION }}-${{ env.DEBIAN_RELEASE }}

      - name: Build and push Docker image (debug)
        uses: docker/build-push-action@v5
        with:
          target: debug
          context: ${{ env.CONTEXT }}
          build-args: ${{ env.BUILD_ARGS }}
          push: true
          labels: ${{ env.LABELS }}
          tags: |
            ${{ env.TAG_BASE }}:debug
            ${{ env.TAG_BASE }}:${{ env.PYTHON_VERSION }}-debug
            ${{ env.TAG_BASE }}:${{ env.PYTHON_VERSION }}-${{ env.DEBIAN_RELEASE }}-debug

      - name: Build and push Docker image (nonroot)
        uses: docker/build-push-action@v5
        with:
          target: nonroot
          context: ${{ env.CONTEXT }}
          build-args: ${{ env.BUILD_ARGS }}
          push: true
          labels: ${{ env.LABELS }}
          tags: |
            ${{ env.TAG_BASE }}:nonroot
            ${{ env.TAG_BASE }}:${{ env.PYTHON_VERSION }}-nonroot
            ${{ env.TAG_BASE }}:${{ env.PYTHON_VERSION }}-${{ env.DEBIAN_RELEASE }}-nonroot

      - name: Build and push Docker image (debug-nonroot)
        uses: docker/build-push-action@v5
        with:
          target: debug-nonroot
          context: ${{ env.CONTEXT }}
          build-args: ${{ env.BUILD_ARGS }}
          push: true
          labels: ${{ env.LABELS }}
          tags: |
            ${{ env.TAG_BASE }}:debug-nonroot
            ${{ env.TAG_BASE }}:${{ env.PYTHON_VERSION }}-debug-nonroot
            ${{ env.TAG_BASE }}:${{ env.PYTHON_VERSION }}-${{ env.DEBIAN_RELEASE }}-debug-nonroot
