name: Build and push images (python)

on:
  workflow_dispatch:

concurrency:
  group: python
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMG_NAME: python
  PYTHON_VERSION: 3.11
  DEBIAN_VERSION: 12

jobs:
  vars:
    runs-on: ubuntu-latest

    steps:
      - run: pwd

    outputs:
      tag_base: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMG_NAME }}
      tag_end1: ${{ env.PYTHON_VERSION }}
      tag_end2: ${{ env.PYTHON_VERSION }}-debian${{ env.DEBIAN_VERSION }}
      context: "{{defaultContext}}:${{ env.IMG_NAME }}"
      labels: |
        org.opencontainers.image.source=${{ github.event.repository.html_url }}
        org.opencontainers.image.description=${{ github.event.repository.description }}
        org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
        org.opencontainers.image.revision=${{ github.sha }}
      build_args: |
        PYTHON_VERSION=${{ env.PYTHON_VERSION }}
        DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}

  build-and-push-images:
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, [self-hosted, arm64]]
    #   fail-fast: false

    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    needs: vars

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and check image (check)
        uses: docker/build-push-action@v6
        with:
          target: check
          context: ${{ needs.vars.outputs.context }}
          build-args: ${{ needs.vars.outputs.build_args }}

      - name: Build and push image (latest)
        uses: docker/build-push-action@v6
        with:
          target: latest
          context: ${{ needs.vars.outputs.context }}
          build-args: ${{ needs.vars.outputs.build_args }}
          push: true
          provenance: false
          labels: ${{ needs.vars.outputs.labels }}
          tags: |
            ${{ needs.vars.outputs.tag_base }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end1 }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end2 }}

      - name: Build and push image (debug)
        env:
          TARGET: debug
        uses: docker/build-push-action@v6
        with:
          target: ${{ env.TARGET }}
          context: ${{ needs.vars.outputs.context }}
          build-args: ${{ needs.vars.outputs.build_args }}
          push: true
          provenance: false
          labels: ${{ needs.vars.outputs.labels }}
          tags: |
            ${{ needs.vars.outputs.tag_base }}:${{ env.TARGET }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end1 }}-${{ env.TARGET }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end2 }}-${{ env.TARGET }}

      - name: Build and push image (nonroot)
        env:
          TARGET: nonroot
        uses: docker/build-push-action@v6
        with:
          target: ${{ env.TARGET }}
          context: ${{ needs.vars.outputs.context }}
          build-args: ${{ needs.vars.outputs.build_args }}
          push: true
          provenance: false
          labels: ${{ needs.vars.outputs.labels }}
          tags: |
            ${{ needs.vars.outputs.tag_base }}:${{ env.TARGET }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end1 }}-${{ env.TARGET }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end2 }}-${{ env.TARGET }}

      - name: Build and push image (debug-nonroot)
        env:
          TARGET: debug-nonroot
        uses: docker/build-push-action@v6
        with:
          target: ${{ env.TARGET }}
          context: ${{ needs.vars.outputs.context }}
          build-args: ${{ needs.vars.outputs.build_args }}
          push: true
          provenance: false
          labels: ${{ needs.vars.outputs.labels }}
          tags: |
            ${{ needs.vars.outputs.tag_base }}:${{ env.TARGET }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end1 }}-${{ env.TARGET }}
            ${{ needs.vars.outputs.tag_base }}:${{ needs.vars.outputs.tag_end2 }}-${{ env.TARGET }}
