name: Build and push Docker images (python)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'

concurrency:
  group: python
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  TAG_BASE: ghcr.io/${{ github.actor }}
  IMG_NAME: python
  LABELS: |
    org.opencontainers.image.source=${{ github.event.repository.html_url }}
    org.opencontainers.image.description=${{ github.event.repository.description }}
    org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}
    org.opencontainers.image.revision=${{ github.sha }}
  PYTHON_VERSION: 3.11
  DEBIAN_VERSION: 12

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and check Docker image (check)
        uses: docker/build-push-action@v4
        with:
          target: check
          context: '{{defaultContext}}:${{ env.IMG_NAME }}'
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}

      - name: Build and push Docker image (latest)
        uses: docker/build-push-action@v4
        with:
          target: latest
          context: '{{defaultContext}}:${{ env.IMG_NAME }}'
          push: true
          labels: ${{ env.LABELS }}
          tags: |
            ${{ env.TAG_BASE }}/${{ env.IMG_NAME }}:latest
            ${{ env.TAG_BASE }}/${{ env.IMG_NAME }}:${{ env.PYTHON_VERSION }}-latest
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}

      - name: Build and push Docker image (debug)
        uses: docker/build-push-action@v4
        with:
          target: debug
          context: '{{defaultContext}}:${{ env.IMG_NAME }}'
          push: true
          labels: ${{ env.LABELS }}
          tags: |
            ${{ env.TAG_BASE }}/${{ env.IMG_NAME }}:debug
            ${{ env.TAG_BASE }}/${{ env.IMG_NAME }}:${{ env.PYTHON_VERSION }}-debug
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}

      - name: Build and push Docker image (nonroot)
        uses: docker/build-push-action@v4
        with:
          target: nonroot
          context: '{{defaultContext}}:${{ env.IMG_NAME }}'
          push: true
          labels: ${{ env.LABELS }}
          tags: |
            ${{ env.TAG_BASE }}/${{ env.IMG_NAME }}:nonroot
            ${{ env.TAG_BASE }}/${{ env.IMG_NAME }}:${{ env.PYTHON_VERSION }}-nonroot
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}

      - name: Build and push Docker image (debug-nonroot)
        uses: docker/build-push-action@v4
        with:
          target: debug-nonroot
          context: '{{defaultContext}}:${{ env.IMG_NAME }}'
          push: true
          labels: ${{ env.LABELS }}
          tags: |
            ${{ env.TAG_BASE }}/${{ env.IMG_NAME }}:debug-nonroot
            ${{ env.TAG_BASE }}/${{ env.IMG_NAME }}:${{ env.PYTHON_VERSION }}-debug-nonroot
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}
